version: "3.8"
services:
  webcctv:
    build: .
    container_name: webcctv-hg680p
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - JWT_SECRET=cctv_hg680p_secret_ganti_ini
      - DB_PATH=/data/cctv.db
      - VIDEO_SIZE=960x540
      - VIDEO_FPS=15
      - VIDEO_BITRATE=800k
      - REC_SIZE=1280x720
    volumes:
      - ./data:/data
      - ./records:/app/public/records
      - ./streams:/app/public/streams
    restart: unless-stopped
